import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import path from "node:path"
import type { Plugin } from "vite"
import { findConfigFile, loadConfig } from "../config/loader"
import { scanSidebar } from "../sidebar/scanner"
import { parseDocument } from "../markdown/parse"
import type { ResolvedConfig } from "../config/types"
import type { ParsedDocument } from "../markdown/types"
import { getTheme, getThemeNames } from "../themes"
import { generateThemeCSS, generateProseCSS } from "../themes/generate-css"
import { buildSearchIndex, stripHtml } from "../search/indexer"
import { loadCache, saveCache, isCached, getCached, setCached } from "../cache/index"

/**
 * Walk up from a directory to find the repository root.
 * Tries multiple markers in priority order:
 * 1. .git directory or file (standard git, worktrees)
 * 2. Lock files (bun.lockb, pnpm-lock.yaml, yarn.lock, package-lock.json)
 * 3. Root config markers (.gitignore, turbo.json, nx.json)
 * 4. Agentic markers (.claude, .cursor, .agents)
 *
 * If no marker is found, returns undefined and filePath falls back
 * to being relative to docsRoot.
 */
function findRepoRoot(startDir: string): string | undefined {
	const markers = [
		// Tier 1: git
		[".git"],
		// Tier 2: lock files (always at repo root)
		["bun.lockb", "pnpm-lock.yaml", "yarn.lock", "package-lock.json"],
		// Tier 3: root config
		[".gitignore", "turbo.json", "nx.json"],
		// Tier 4: agentic / editor
		[".claude", ".cursor", ".agents"],
	]

	// Walk up once, checking all tiers at each level (highest tier wins)
	let dir = path.resolve(startDir)
	const { root: fsRoot } = path.parse(dir)
	const candidates: Array<{ dir: string; tier: number }> = []

	while (true) {
		for (let tier = 0; tier < markers.length; tier++) {
			for (const marker of markers[tier]) {
				if (existsSync(path.join(dir, marker))) {
					candidates.push({ dir, tier })
				}
			}
		}
		if (dir === fsRoot) break
		dir = path.dirname(dir)
	}

	if (candidates.length === 0) return undefined

	// Return the best match: lowest tier number wins, deepest dir breaks ties
	candidates.sort((a, b) => a.tier - b.tier)
	return candidates[0].dir
}

/** In-memory state holding config, sidebar, and parsed documents */
interface PetitState {
	config: ResolvedConfig
	sidebar: Array<{
		label: string
		entries: Array<{ label: string; slug: string; draft: boolean }>
	}>
	docs: Record<
		string,
		{
			html: string
			raw: string
			filePath: string
			frontmatter: ParsedDocument["frontmatter"]
			headings: ParsedDocument["headings"]
			lastModified: string
		}
	>
}

/** Load config, scan sidebar, and parse all documents into memory */
async function buildState(configPath: string, useCache = true): Promise<PetitState> {
	const config = await loadConfig(configPath)
	const theme = getTheme(config.theme)
	const sidebar = await scanSidebar(config)
	const docs: PetitState["docs"] = {}
	const cacheKey = `${theme.shiki.light}:${theme.shiki.dark}`
	const cache = useCache ? loadCache(cacheKey) : {}

	// Find repo root to compute repo-relative file paths
	const repoRoot = findRepoRoot(config.docsRoot)
	if (!repoRoot && config.repository) {
		console.warn("[petit] Could not detect repo root for GitHub links. Initialize git or add a .gitignore at your project root.")
	}

	for (const category of sidebar) {
		for (const entry of category.entries) {
			const fileContent = readFileSync(entry.filePath, "utf-8")
			let parsed: ParsedDocument

			if (useCache && isCached(cache, entry.filePath, fileContent)) {
				parsed = getCached(cache, entry.filePath)!
			} else {
				parsed = await parseDocument(entry.filePath, { shikiThemes: { light: theme.shiki.light, dark: theme.shiki.dark } })
				if (useCache) setCached(cache, entry.filePath, fileContent, parsed)
			}

			const stats = statSync(entry.filePath)
			docs[entry.slug] = {
				html: parsed.html,
				raw: parsed.raw,
				frontmatter: parsed.frontmatter,
				headings: parsed.headings,
				filePath: repoRoot
					? path.relative(repoRoot, entry.filePath).replace(/\\/g, "/")
					: path.relative(config.docsRoot, entry.filePath).replace(/\\/g, "/"),
				lastModified: stats.mtime.toISOString(),
			}
		}
	}

	if (useCache) saveCache(cache, cacheKey)

	return {
		config,
		sidebar: sidebar.map((cat) => ({
			label: cat.label,
			entries: cat.entries.map((e) => ({
				label: e.label,
				slug: e.slug,
				draft: e.draft,
			})),
		})),
		docs,
	}
}

/** Write error state files when config validation fails */
function writeErrorFiles(appRoot: string, error: string): void {
	const outDir = path.join(appRoot, "src", ".petit")
	if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })

	writeFileSync(
		path.join(outDir, "error.ts"),
		`// Auto-generated by petit\nexport const configError: string | null = ${JSON.stringify(error)}\n`,
		"utf-8",
	)
	writeFileSync(
		path.join(outDir, "config.ts"),
		`// Auto-generated by petit — config error\nexport const config = { title: "petit", defaultScheme: "system", schemeSwitcher: true, theme: "default", themeOverrides: {}, logo: null, maxWidth: "md", sidebarPosition: "left", toc: true, repository: null, branch: "main", siteUrl: null, favicon: null, shiki: { light: "github-light", dark: "github-dark" } } as { title: string; defaultScheme: "dark" | "light" | "system"; schemeSwitcher: boolean; theme: string; themeOverrides: Record<string, unknown>; logo: string | null; maxWidth: "sm" | "md" | "lg" | "xl"; sidebarPosition: "left" | "right" | "center"; toc: boolean; repository: string | null; branch: string; siteUrl: string | null; favicon: string | null; shiki: { light: string; dark: string } }\n`,
		"utf-8",
	)
	writeFileSync(
		path.join(outDir, "sidebar.ts"),
		`// Auto-generated by petit — config error\nexport const sidebar: Array<{ label: string; entries: Array<{ label: string; slug: string; draft: boolean }> }> = []\n`,
		"utf-8",
	)
	writeFileSync(
		path.join(outDir, "docs.ts"),
		`// Auto-generated by petit — config error\nexport const docs: Record<string, { html: string; raw: string; filePath: string; frontmatter: { title?: string; description?: string; order?: number; draft?: boolean }; headings: Array<{ depth: number; text: string; id: string }>; lastModified: string }> = {}\n`,
		"utf-8",
	)
	writeFileSync(
		path.join(outDir, "theme.css"),
		"/* petit — config error */\n",
		"utf-8",
	)
	writeFileSync(
		path.join(outDir, "search.ts"),
		`// Auto-generated by petit — config error\nexport const searchIndex = null\n`,
		"utf-8",
	)
	writeFileSync(
		path.join(outDir, "themes.ts"),
		`// Auto-generated by petit — config error\nexport const themes: Record<string, { light: Record<string, string>; dark: Record<string, string> }> = {}\n`,
		"utf-8",
	)
}

/** Write generated .ts files that app routes import from */
async function writeGeneratedFiles(appRoot: string, state: PetitState): Promise<void> {
	const outDir = path.join(appRoot, "src", ".petit")
	if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })

	const theme = getTheme(state.config.theme)

	writeFileSync(
		path.join(outDir, "theme.css"),
		generateThemeCSS(theme, state.config.fonts) + "\n" + generateProseCSS(theme),
		"utf-8",
	)

	// Detect and copy custom favicon from media/
	let favicon: string | null = null
	const publicDir = path.join(appRoot, "public")
	for (const candidate of ["favicon.ico", "favicon.png", "logo.png"]) {
		const userFavicon = path.join(state.config.mediaRoot, candidate)
		if (existsSync(userFavicon)) {
			writeFileSync(path.join(publicDir, candidate), readFileSync(userFavicon))
			favicon = `/${candidate}`
			break
		}
	}

	// Generate PWA manifest
	const manifest = {
		name: state.config.title,
		short_name: state.config.title,
		description: `${state.config.title} documentation`,
		start_url: "/",
		display: "standalone",
		theme_color: "#000000",
		background_color: "#000000",
		icons: [
			...(favicon ? [{ src: favicon, type: favicon.endsWith(".png") ? "image/png" : "image/x-icon", sizes: "any" }] : []),
		],
	}
	writeFileSync(
		path.join(publicDir, "manifest.json"),
		JSON.stringify(manifest, null, "\t"),
		"utf-8",
	)

	writeFileSync(
		path.join(outDir, "config.ts"),
		`// Auto-generated by petit — do not edit\nexport const config = ${JSON.stringify(
			{
				title: state.config.title,
				defaultScheme: state.config.defaultScheme,
				schemeSwitcher: state.config.schemeSwitcher,
				theme: state.config.theme,
				themeOverrides: state.config.themeOverrides,
				logo: state.config.logoPath
					? "/" + path.relative(state.config.docsRoot, state.config.logoPath).replace(/\\/g, "/")
					: null,
				maxWidth: state.config.maxWidth,
				sidebarPosition: state.config.sidebarPosition,
				toc: state.config.toc,
				repository: state.config.repository ?? null,
				branch: state.config.branch,
				siteUrl: state.config.siteUrl ?? null,
				favicon,
				shiki: {
					light: theme.shiki.light,
					dark: theme.shiki.dark,
				},
			},
			null,
			"\t",
		)} as { title: string; defaultScheme: "dark" | "light" | "system"; schemeSwitcher: boolean; theme: string; themeOverrides: Record<string, unknown>; logo: string | null; maxWidth: "sm" | "md" | "lg" | "xl"; sidebarPosition: "left" | "right" | "center"; toc: boolean; repository: string | null; branch: string; siteUrl: string | null; favicon: string | null; shiki: { light: string; dark: string } }\n`,
		"utf-8",
	)

	writeFileSync(
		path.join(outDir, "sidebar.ts"),
		`// Auto-generated by petit — do not edit\nexport const sidebar: Array<{ label: string; entries: Array<{ label: string; slug: string; draft: boolean }> }> = ${JSON.stringify(state.sidebar, null, "\t")}\n`,
		"utf-8",
	)

	writeFileSync(
		path.join(outDir, "docs.ts"),
		`// Auto-generated by petit — do not edit\nexport const docs: Record<string, { html: string; raw: string; filePath: string; frontmatter: { title?: string; description?: string; order?: number; draft?: boolean }; headings: Array<{ depth: number; text: string; id: string }>; lastModified: string }> = ${JSON.stringify(state.docs)}\n`,
		"utf-8",
	)

	writeFileSync(
		path.join(outDir, "error.ts"),
		`// Auto-generated by petit\nexport const configError: string | null = null\n`,
		"utf-8",
	)

	// Build and write search index
	const searchDocs: Array<{
		slug: string
		title: string
		description: string
		content: string
		category: string
		headingId: string
	}> = []
	for (const cat of state.sidebar) {
		for (const entry of cat.entries) {
			if (entry.draft) continue
			const doc = state.docs[entry.slug]
			if (!doc) continue

			const pageTitle = doc.frontmatter.title ?? entry.label
			const pageContent = stripHtml(doc.html)

			// Index the full page
			searchDocs.push({
				slug: entry.slug,
				title: pageTitle,
				description: doc.frontmatter.description ?? "",
				content: pageContent,
				category: cat.label,
				headingId: "",
			})

			// Index each heading as a separate entry
			for (const heading of doc.headings) {
				if (heading.depth < 2 || heading.depth > 3) continue
				searchDocs.push({
					slug: entry.slug,
					title: heading.text,
					description: pageTitle,
					content: "",
					category: cat.label,
					headingId: heading.id,
				})
			}
		}
	}
	const { serialized } = await buildSearchIndex(searchDocs)
	writeFileSync(
		path.join(outDir, "search.ts"),
		`// Auto-generated by petit — do not edit\nexport const searchIndex = ${JSON.stringify(serialized)}\n`,
		"utf-8",
	)

	// Write all theme definitions for client-side preview
	const allThemes: Record<string, { light: Record<string, string>; dark: Record<string, string> }> = {}
	for (const name of getThemeNames()) {
		const t = getTheme(name)
		allThemes[name] = {
			light: { ...t.light } as Record<string, string>,
			dark: { ...t.dark } as Record<string, string>,
		}
	}
	writeFileSync(
		path.join(outDir, "themes.ts"),
		`// Auto-generated by petit — do not edit\nexport const themes: Record<string, { light: Record<string, string>; dark: Record<string, string> }> = ${JSON.stringify(allThemes)}\n`,
		"utf-8",
	)
}

/**
 * Vite plugin for petit docs.
 * Finds petit.config.json, loads docs, writes generated files to src/.petit/,
 * and watches for changes during dev.
 */
export function petitPlugin(): Plugin {
	let state: PetitState | null = null
	let configPath: string | undefined
	let appRoot = ""
	let isDev = false

	return {
		name: "petit",
		enforce: "pre",

		async configResolved(viteConfig) {
			appRoot = viteConfig.root
			isDev = viteConfig.command === "serve"

			// Search from vite root upward for petit.config.json
			configPath = findConfigFile(appRoot)

			if (!configPath) {
				console.warn("[petit] No petit.config.json found (searched from", appRoot, "upward)")
				return
			}

			console.log("[petit] Found config:", configPath)

			try {
				state = await buildState(configPath, !isDev)
				await writeGeneratedFiles(appRoot, state)
				console.log(`[petit] Loaded ${Object.keys(state.docs).length} documents`)
			} catch (err) {
				const message = err instanceof Error ? err.message : String(err)
				console.error("[petit] Config error:", message)
				writeErrorFiles(appRoot, message)
			}
		},

		configureServer(server) {
			if (!state || !configPath) return

			const docsRoot = state.config.docsRoot
			const mediaRoot = state.config.mediaRoot

			if (existsSync(mediaRoot)) {
				const mimeTypes: Record<string, string> = {
					".png": "image/png",
					".jpg": "image/jpeg",
					".jpeg": "image/jpeg",
					".gif": "image/gif",
					".svg": "image/svg+xml",
					".webp": "image/webp",
					".mp4": "video/mp4",
					".webm": "video/webm",
					".ico": "image/x-icon",
				}

				server.middlewares.use("/media", (req, res, next) => {
					const filePath = path.join(mediaRoot, decodeURIComponent(req.url || ""))
					if (existsSync(filePath)) {
						const ext = path.extname(filePath).toLowerCase()
						res.setHeader("Content-Type", mimeTypes[ext] || "application/octet-stream")
						res.end(readFileSync(filePath))
						return
					}
					next()
				})
			}

			// Serve raw markdown files and LLM index in dev mode
			server.middlewares.use((req, res, next) => {
				if (!state || !req.url) return next()
				const url = decodeURIComponent(req.url).replace(/^\//, "")

				// llms-full.md — all docs concatenated
				if (url === "llms-full.md") {
					const sections: string[] = [`# ${state.config.title} — Full Documentation`, ""]
					for (const cat of state.sidebar) {
						sections.push(`## ${cat.label}`, "")
						for (const entry of cat.entries) {
							if (entry.draft) continue
							const doc = state.docs[entry.slug]
							if (!doc) continue
							const title = doc.frontmatter.title ?? entry.label
							sections.push(`### ${title}`)
							if (doc.frontmatter.description) {
								sections.push("", `> ${doc.frontmatter.description}`)
							}
							sections.push("", doc.raw.trim(), "", "---", "")
						}
					}
					res.setHeader("Content-Type", "text/markdown; charset=utf-8")
					res.end(sections.join("\n"))
					return
				}

				// llms.txt — LLM discoverability index
				if (url === "llms.txt") {
					const base = state.config.siteUrl?.replace(/\/$/, "") ?? ""
					const lines: string[] = [
						`# ${state.config.title}`,
						"",
						`> ${state.config.title} documentation`,
						"",
						"## Docs",
						"",
					]
					for (const cat of state.sidebar) {
						for (const entry of cat.entries) {
							if (entry.draft) continue
							lines.push(`- [${entry.label}](${base}/${entry.slug}.md)`)
						}
					}
					lines.push("")
					res.setHeader("Content-Type", "text/plain; charset=utf-8")
					res.end(lines.join("\n"))
					return
				}

				// Individual .md files — {slug}.md serves raw markdown
				if (url.endsWith(".md")) {
					const slug = url.slice(0, -3)
					const doc = state.docs[slug]
					if (doc) {
						const parts: string[] = []
						if (doc.frontmatter.title) {
							parts.push(`# ${doc.frontmatter.title}`)
							if (doc.frontmatter.description) {
								parts.push("", `> ${doc.frontmatter.description}`)
							}
							parts.push("")
						}
						parts.push(doc.raw.trim(), "")
						res.setHeader("Content-Type", "text/markdown; charset=utf-8")
						res.end(parts.join("\n"))
						return
					}
				}

				next()
			})

			// Watch docs directory and config file for changes
			server.watcher.add(docsRoot)
			server.watcher.add(configPath)

			let debounceTimer: ReturnType<typeof setTimeout> | null = null

			server.watcher.on("all", (_event: string, filePath: string) => {
				if (!filePath) return
				const norm = path.normalize(filePath)
				const ext = path.extname(norm)
				const isDoc = ext === ".md" || ext === ".mdx"
				const isConfig = norm === path.normalize(configPath!)
				const isGenerated = norm.includes(path.join("src", ".petit"))

				if (isGenerated || (!isDoc && !isConfig)) return

				if (debounceTimer) clearTimeout(debounceTimer)
				debounceTimer = setTimeout(async () => {
					try {
						console.log("[petit] Change detected, rebuilding...")
						state = await buildState(configPath!, false)
						await writeGeneratedFiles(appRoot, state)
						console.log(`[petit] Rebuilt ${Object.keys(state.docs).length} documents`)
					} catch (err) {
						console.error("[petit] Rebuild failed:", err)
					}
				}, 300)
			})
		},
	}
}
