import type { ThemeDefinition, ThemeColors } from "./types"

/** Font overrides from user config */
export interface FontOverrides {
	/** Sans-serif font for body text */
	sans?: string
	/** Monospace font for code */
	mono?: string
}

/** Convert a ThemeColors record to CSS variable declarations */
function colorsToVars(colors: ThemeColors): string {
	return Object.entries(colors)
		.map(([key, value]) => `\t--${key}: ${value};`)
		.join("\n")
}

/** Build a Google Fonts @import URL for the given font names */
function googleFontsImport(fonts: FontOverrides): string {
	const families: string[] = []
	if (fonts.sans) families.push(`family=${encodeURIComponent(fonts.sans)}:wght@400;500;600;700`)
	if (fonts.mono) families.push(`family=${encodeURIComponent(fonts.mono)}:wght@400;500;600;700`)
	if (families.length === 0) return ""
	return `@import url("https://fonts.googleapis.com/css2?${families.join("&")}&display=swap");\n\n`
}

/** Build font CSS variable overrides */
function fontVars(fonts: FontOverrides): string {
	const lines: string[] = []
	if (fonts.sans) lines.push(`\t--font-sans: "${fonts.sans}", system-ui, sans-serif;`)
	if (fonts.mono) lines.push(`\t--font-mono: "${fonts.mono}", monospace;`)
	return lines.join("\n")
}

/**
 * Generate the complete CSS variable declarations for a theme (light + dark).
 * When fontOverrides are provided, a Google Fonts import is prepended and
 * --font-sans / --font-mono CSS variables are overridden.
 */
export function generateThemeCSS(theme: ThemeDefinition, fontOverrides?: FontOverrides): string {
	const fontsImport = fontOverrides ? googleFontsImport(fontOverrides) : ""
	const fontVarBlock = fontOverrides ? fontVars(fontOverrides) : ""
	const fontSection = fontVarBlock ? `\n${fontVarBlock}` : ""

	return `${fontsImport}/* Generated by petit — theme: ${theme.name} */
:root {
${colorsToVars(theme.light)}${fontSection}
}

.dark {
${colorsToVars(theme.dark)}
}
`
}

/** Generate prose/typography CSS from a theme */
export function generateProseCSS(theme: ThemeDefinition): string {
	const p = theme.prose
	return `/* Generated by petit — prose */
.prose {
	font-size: ${p.body};
	line-height: ${p.lineHeight};
}

.prose :where(h1):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-size: ${p.headings.h1};
	font-weight: 700;
	letter-spacing: -0.025em;
	margin-top: 0;
	margin-bottom: 1rem;
	line-height: 1.2;
}

.prose :where(h2):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-size: ${p.headings.h2};
	font-weight: 600;
	letter-spacing: -0.02em;
	margin-top: 2.5rem;
	margin-bottom: 0.75rem;
	line-height: 1.3;
	padding-bottom: 0.5rem;
	border-bottom: 1px solid var(--border);
}

.prose :where(h3):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-size: ${p.headings.h3};
	font-weight: 600;
	margin-top: 2rem;
	margin-bottom: 0.5rem;
	line-height: 1.4;
}

.prose :where(h4):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-size: ${p.headings.h4};
	font-weight: 600;
	margin-top: 1.5rem;
	margin-bottom: 0.5rem;
	line-height: 1.4;
}

.prose :where(p):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	margin-top: 0.75rem;
	margin-bottom: 0.75rem;
}

.prose :where(a):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-weight: 500;
	text-decoration: underline;
	text-underline-offset: 2px;
	text-decoration-color: var(--border);
	transition: text-decoration-color 0.15s;
}

.prose :where(a):not(:where([class~="not-prose"],[class~="not-prose"] *)):hover {
	text-decoration-color: var(--foreground);
}

.prose :where(code):not(:where([class~="not-prose"],[class~="not-prose"] *)):not(pre code) {
	font-size: 0.8125em;
	font-weight: 500;
	padding: 0.2em 0.4em;
	border-radius: 0.25rem;
	background: var(--muted);
}

.prose :where(code):not(:where([class~="not-prose"],[class~="not-prose"] *)):not(pre code)::before,
.prose :where(code):not(:where([class~="not-prose"],[class~="not-prose"] *)):not(pre code)::after {
	content: none;
}

:root:not(.dark) .shiki,
:root:not(.dark) .shiki span {
	color: var(--shiki-light) !important;
	background-color: var(--shiki-light-bg) !important;
	font-style: var(--shiki-light-font-style) !important;
	font-weight: var(--shiki-light-font-weight) !important;
	text-decoration: var(--shiki-light-text-decoration) !important;
}

.prose :where(pre):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-size: 0.8125rem;
	line-height: 1.7;
	border-radius: ${p.codeRadius};
	padding: 1rem 1.25rem;
	border: 1px solid var(--border);
	margin-top: 1.25rem;
	margin-bottom: 1.25rem;
}

.prose :where(ul):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	padding-left: 1.25rem;
}

.prose :where(ol):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	padding-left: 1.25rem;
}

.prose :where(li):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	margin-top: 0.25rem;
	margin-bottom: 0.25rem;
}

.prose :where(table):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-size: 0.875rem;
}

.prose :where(th):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-weight: 600;
	padding: 0.5rem 0.75rem;
}

.prose :where(td):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	padding: 0.5rem 0.75rem;
}

.prose :where(blockquote):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	border-left: 3px solid var(--border);
	padding-left: 1rem;
	font-style: normal;
	color: var(--muted-foreground);
}

.prose :where(hr):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	border-color: var(--border);
	margin-top: 2rem;
	margin-bottom: 2rem;
}

.prose :where(strong):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
	font-weight: 600;
}

.petit-dark-only { display: none; }
.petit-light-only { display: block; }
.dark .petit-dark-only { display: block; }
.dark .petit-light-only { display: none; }

.petit-copy-heading {
	display: inline-flex;
	align-items: center;
	justify-content: center;
	width: 1.25rem;
	height: 1.25rem;
	margin-left: 0.375rem;
	color: var(--muted-foreground);
	opacity: 0;
	transition: opacity 0.15s;
	cursor: pointer;
	vertical-align: middle;
	border: none;
	background: none;
	padding: 0;
	border-radius: 0.25rem;
}
.petit-copy-heading:hover { color: var(--foreground); }
:where(h2, h3, h4):hover .petit-copy-heading { opacity: 1; }
.petit-copy-heading.copied { opacity: 1; color: var(--primary); }

.petit-callout {
	border-radius: var(--radius);
	padding: 0.875rem 1rem;
	margin: 1.25rem 0;
	font-size: 0.8125rem;
	background: var(--muted);
	border: 1px solid var(--border);
}
.petit-callout-title {
	display: flex;
	align-items: center;
	gap: 0.375rem;
	font-weight: 600;
	font-size: 0.75rem;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--muted-foreground);
	margin-bottom: 0.375rem;
}
.petit-callout-title svg { flex-shrink: 0; }
.petit-callout-note .petit-callout-title svg,
.petit-callout-info .petit-callout-title svg { color: var(--primary); }
.petit-callout-tip .petit-callout-title svg { color: var(--accent-foreground); }
.petit-callout-warning .petit-callout-title svg { color: var(--ring); }
.petit-callout-danger .petit-callout-title svg { color: var(--destructive); }
.petit-callout-content p { margin: 0.25rem 0; }
.petit-callout-content p:last-child { margin-bottom: 0; }

@media print {
	.petit-sidebar, nav, .petit-toc, header, footer,
	[data-slot="sidebar"], [data-slot="sidebar-trigger"],
	.petit-search, button, .petit-doc-actions { display: none !important; }

	body { background: white !important; color: black !important; }

	article { max-width: 100% !important; padding: 0 !important; margin: 0 !important; }

	pre { white-space: pre-wrap !important; word-wrap: break-word !important; }

	a[href]::after { content: " (" attr(href) ")"; font-size: 0.8em; color: #666; }
	a[href^="#"]::after, a[href^="javascript:"]::after { content: none; }

	h1, h2, h3, h4 { page-break-after: avoid; }
	pre, blockquote, table { page-break-inside: avoid; }
}
`
}
